import type { UserProfile, Intent } from '../types/auth';

export interface DemoPersona {
  email: string;
  password: string;
  name: string;
  role: string;
  tagline: string;
  intent: Intent;
  avatar: string;
  user: UserProfile;
}

export const DEMO_PERSONAS: DemoPersona[] = [
  {
    email: 'demo1@example.com',
    password: 'PropVibe-demo-2026',
    name: 'Aarav Shah',
    role: 'Software Engineer',
    tagline: 'Seeking roommate for 2BHK in Navrangpura. Early bird, loves quiet coffee mornings.',
    intent: 'seek_roommate',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    user: {
      id: 'demo-user-1',
      email: 'demo1@example.com',
      created_at: new Date().toISOString(),
      profile: {
        full_name: 'Aarav Shah',
        age: 24,
        gender: 'man',
        occupation: 'Software Engineer',
        bio: 'Tech lead working hybrid. Looking for a mindful, tidy roommate who values calm evenings and mutual respect.',
        intent: 'seek_roommate',
        search: {
          location: {
            city: 'Ahmedabad',
            areas: ['Navrangpura', 'Naranpura'],
            pincodes: ['380009'],
            nearby: [{ kind: 'jain_derasar', max_distance_km: 2, importance: 'preferred' }],
          },
          budget: { minimum: 6000, maximum: 16000 },
          property_types: ['1bhk', '2bhk'],
          move_in_from: '2026-10-01',
          move_in_by: '2026-11-01',
          stay_months: 12,
        },
        lifestyle: {
          cleanliness: 4,
          social_energy: 3,
          guests: 2,
          noise_tolerance: 2,
          sleep_schedule: 'early_bird',
          work_style: 'hybrid',
          diet: 'vegetarian',
          smokes: false,
          has_pets: false,
        },
        roommate_preferences: {
          genders: [],
          smoking_ok: false,
          pets_ok: true,
          diets: ['vegetarian', 'jain', 'vegan'],
        },
        compatibility_weights: {
          cleanliness: 4,
          social_energy: 3,
          guests: 3,
          noise_tolerance: 4,
          sleep_schedule: 3,
          work_style: 2,
          diet: 3,
          smokes: 4,
          has_pets: 2,
        },
        room_priorities: {
          size: 3,
          private_bathroom: 4,
          balcony: 3,
          natural_light: 4,
          quiet: 5,
        },
      },
      offering: null,
      media: {
        photos: [
          {
            id: 'm1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 154000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 1,
            caption: 'Weekend filter coffee routine',
            created_at: new Date().toISOString(),
          },
          {
            id: 'm2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 142000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 2,
            caption: 'Working from creative spaces',
            created_at: new Date().toISOString(),
          },
          {
            id: 'm3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 139000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 3,
            caption: 'Plant lover and design enthusiast',
            created_at: new Date().toISOString(),
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
      onboarding: {
        complete: true,
        profile_photos_needed: 0,
        property_photos_needed: 0,
        next_steps: [],
      },
    },
  },
  {
    email: 'demo2@example.com',
    password: 'PropVibe-demo-2026',
    name: 'Meera Patel',
    role: 'UX Designer',
    tagline: 'Seeking roommate for shared apartment. Aesthetic spaces, plants & music.',
    intent: 'seek_roommate',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    user: {
      id: 'demo-user-2',
      email: 'demo2@example.com',
      created_at: new Date().toISOString(),
      profile: {
        full_name: 'Meera Patel',
        age: 23,
        gender: 'woman',
        occupation: 'Product Designer',
        bio: 'Obsessed with mid-century furniture and pottery. Looking for a clean, warm living vibe with great sunlight.',
        intent: 'seek_roommate',
        search: {
          location: {
            city: 'Ahmedabad',
            areas: ['Navrangpura', 'Vastrapur'],
            pincodes: ['380009', '380015'],
            nearby: [],
          },
          budget: { minimum: 7000, maximum: 17000 },
          property_types: ['2bhk', '3bhk'],
          move_in_from: '2026-10-15',
          move_in_by: '2026-11-15',
          stay_months: 12,
        },
        lifestyle: {
          cleanliness: 5,
          social_energy: 4,
          guests: 3,
          noise_tolerance: 3,
          sleep_schedule: 'night_owl',
          work_style: 'remote',
          diet: 'vegetarian',
          smokes: false,
          has_pets: true,
        },
        roommate_preferences: {
          genders: ['woman'],
          smoking_ok: false,
          pets_ok: true,
          diets: [],
        },
        compatibility_weights: {
          cleanliness: 5,
          social_energy: 3,
          guests: 3,
          noise_tolerance: 3,
          sleep_schedule: 3,
          work_style: 2,
          diet: 2,
          smokes: 5,
          has_pets: 3,
        },
        room_priorities: {
          size: 4,
          private_bathroom: 4,
          balcony: 5,
          natural_light: 5,
          quiet: 3,
        },
      },
      offering: null,
      media: {
        photos: [
          {
            id: 'm4',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 154000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 1,
            caption: 'Design studio days',
            created_at: new Date().toISOString(),
          },
          {
            id: 'm5',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 148000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 2,
            caption: 'Sunday farmers market',
            created_at: new Date().toISOString(),
          },
          {
            id: 'm6',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 145000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 3,
            caption: 'Cozy weekend balcony setup',
            created_at: new Date().toISOString(),
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
      onboarding: {
        complete: true,
        profile_photos_needed: 0,
        property_photos_needed: 0,
        next_steps: [],
      },
    },
  },
  {
    email: 'demo6@example.com',
    password: 'PropVibe-demo-2026',
    name: 'Kabir Desai',
    role: 'Financial Analyst',
    tagline: 'Offering private room in 2BHK flatshare (Navrangpura, ₹11,000/mo)',
    intent: 'offer_shared_home',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    user: {
      id: 'demo-user-6',
      email: 'demo6@example.com',
      created_at: new Date().toISOString(),
      profile: {
        full_name: 'Kabir Desai',
        age: 27,
        gender: 'man',
        occupation: 'Financial Analyst',
        bio: 'Have a quiet master bedroom with attached bathroom available in a modern 2BHK flat in Navrangpura.',
        intent: 'offer_shared_home',
        search: null,
        lifestyle: {
          cleanliness: 4,
          social_energy: 3,
          guests: 2,
          noise_tolerance: 2,
          sleep_schedule: 'early_bird',
          work_style: 'office',
          diet: 'vegetarian',
          smokes: false,
          has_pets: false,
        },
        roommate_preferences: {
          genders: [],
          smoking_ok: false,
          pets_ok: false,
          diets: [],
        },
        compatibility_weights: {
          cleanliness: 4,
          social_energy: 3,
          guests: 3,
          noise_tolerance: 3,
          sleep_schedule: 3,
          work_style: 2,
          diet: 2,
          smokes: 4,
          has_pets: 2,
        },
        room_priorities: {
          size: 3,
          private_bathroom: 4,
          balcony: 3,
          natural_light: 4,
          quiet: 4,
        },
      },
      offering: {
        id: 'listing-6',
        owner_id: 'demo-user-6',
        created_at: new Date().toISOString(),
        title: 'Spacious Private Bedroom in Navrangpura 2BHK',
        description: 'Sunny room with attached bath, high-speed WiFi, modular kitchen access, and peaceful balcony.',
        kind: 'private_room',
        property_type: '2bhk',
        provider_relationship: 'tenant',
        location: {
          city: 'Ahmedabad',
          area: 'Navrangpura',
          pincode: '380009',
        },
        monthly_rent: 11000,
        deposit: 11000,
        available_from: '2026-10-01',
        minimum_stay_months: 6,
        available_spaces: 1,
        furnishing: 'semi_furnished',
        amenities: ['attached_bathroom', 'balcony', 'high_speed_wifi', 'washing_machine'],
        nearby_landmarks: [
          { kind: 'public_transport', name: 'Navrangpura Bus Depot', distance_km: 0.4 },
          { kind: 'university', name: 'Ahmedabad University', distance_km: 1.1 },
        ],
        is_active: true,
        media: {
          photos: [
            {
              id: 'prop-1',
              kind: 'photo',
              url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
              thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=200&auto=format&fit=crop&q=80',
              content_type: 'image/jpeg',
              byte_size: 198000,
              width: 800,
              height: 600,
              duration_seconds: null,
              position: 1,
              caption: 'Sunlit bedroom view',
              created_at: new Date().toISOString(),
            },
            {
              id: 'prop-2',
              kind: 'photo',
              url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
              thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200&auto=format&fit=crop&q=80',
              content_type: 'image/jpeg',
              byte_size: 180000,
              width: 800,
              height: 600,
              duration_seconds: null,
              position: 2,
              caption: 'Living room and work nook',
              created_at: new Date().toISOString(),
            },
            {
              id: 'prop-3',
              kind: 'photo',
              url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=800&auto=format&fit=crop&q=80',
              thumbnail_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=200&auto=format&fit=crop&q=80',
              content_type: 'image/jpeg',
              byte_size: 172000,
              width: 800,
              height: 600,
              duration_seconds: null,
              position: 3,
              caption: 'Modular shared kitchen',
              created_at: new Date().toISOString(),
            },
          ],
          video: null,
          cover_photo_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
          photo_count: 3,
          minimum_photos: 3,
          maximum_photos: 6,
          ready: true,
        },
      },
      media: {
        photos: [
          {
            id: 'm7',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 154000,
            width: 800,
            height: 1000,
            duration_seconds: null,
            position: 1,
            caption: 'Kabir',
            created_at: new Date().toISOString(),
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
        photo_count: 1,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
      onboarding: {
        complete: true,
        profile_photos_needed: 0,
        property_photos_needed: 0,
        next_steps: [],
      },
    },
  },
  {
    email: 'demo8@example.com',
    password: 'PropVibe-demo-2026',
    name: 'Rohan Shah',
    role: 'Property Owner',
    tagline: 'Entire 2BHK in Navrangpura (₹24,000/mo, verified stay)',
    intent: 'offer_entire_home',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    user: {
      id: 'demo-user-8',
      email: 'demo8@example.com',
      created_at: new Date().toISOString(),
      profile: {
        full_name: 'Rohan Shah',
        age: 32,
        gender: 'man',
        occupation: 'Property Manager',
        bio: 'Professional landlord offering well-maintained residential apartments with transparent leases and fast maintenance.',
        intent: 'offer_entire_home',
        search: null,
        lifestyle: null,
        roommate_preferences: { genders: [], smoking_ok: null, pets_ok: null, diets: [] },
        compatibility_weights: { cleanliness: 3, social_energy: 3, guests: 3, noise_tolerance: 3, sleep_schedule: 3, work_style: 2, diet: 2, smokes: 3, has_pets: 2 },
        room_priorities: { size: 3, private_bathroom: 3, balcony: 3, natural_light: 3, quiet: 3 },
      },
      offering: {
        id: 'listing-8',
        owner_id: 'demo-user-8',
        created_at: new Date().toISOString(),
        title: 'Bright 2BHK in Heart of Navrangpura',
        description: 'Prime location, reserved parking, 24x7 water supply, elevator, modular kitchen, and park view.',
        kind: 'entire_home',
        property_type: '2bhk',
        provider_relationship: 'owner',
        location: {
          city: 'Ahmedabad',
          area: 'Navrangpura',
          pincode: '380009',
        },
        monthly_rent: 24000,
        deposit: 48000,
        available_from: '2026-10-01',
        minimum_stay_months: 11,
        available_spaces: 1,
        furnishing: 'semi_furnished',
        amenities: ['parking', 'elevator', 'security', 'power_backup'],
        nearby_landmarks: [
          { kind: 'park', name: 'Law Garden', distance_km: 0.8 },
          { kind: 'grocery', name: 'Supermarket', distance_km: 0.2 },
        ],
        is_active: true,
        media: {
          photos: [
            {
              id: 'prop-4',
              kind: 'photo',
              url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
              thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200&auto=format&fit=crop&q=80',
              content_type: 'image/jpeg',
              byte_size: 198000,
              width: 800,
              height: 600,
              duration_seconds: null,
              position: 1,
              caption: 'Spacious hall with balcony',
              created_at: new Date().toISOString(),
            },
          ],
          video: null,
          cover_photo_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
          photo_count: 1,
          minimum_photos: 3,
          maximum_photos: 6,
          ready: true,
        },
      },
      media: {
        photos: [],
        video: null,
        cover_photo_url: null,
        photo_count: 0,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
      onboarding: {
        complete: true,
        profile_photos_needed: 0,
        property_photos_needed: 0,
        next_steps: [],
      },
    },
  },
];
