import type { ListingFeedItem } from '../types/feed';

export const MOCK_LISTINGS: ListingFeedItem[] = [
  {
    listing: {
      id: 'listing-bodakdev-1',
      owner_id: 'provider-aarav',
      title: 'Shivalik Edge High-Rise Flat',
      description: 'Sun-drenched 3BHK flat in a premier gated high-rise society in Bodakdev. 11ft ceilings, Italian marble flooring, expansive balcony overlooking lush green gardens, modular kitchen with piped gas, and Voltas inverter ACs in every bedroom.',
      kind: 'entire_home',
      property_type: '3bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Bodakdev',
        pincode: '380054',
      },
      monthly_rent: 36000,
      deposit: 72000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 3,
        },
        notes: 'Torrent Power actual bill split equally 3 ways via UPI every month.',
      },
      air_conditioning: {
        available: true,
        locations: ['Master Bedroom', 'Bedroom 2', 'Bedroom 3', 'Living Room'],
        billing_method: 'included_in_electricity',
        notes: 'Voltas 1.5-ton split inverter ACs installed in all rooms.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 3,
      furnishing: 'semi_furnished',
      amenities: ['Modular Kitchen', 'Piped Gas', 'Balcony Garden', 'Club House Gym', 'Covered Parking', '24/7 Security'],
      nearby_landmarks: [
        { kind: 'workplace', name: 'Judges Bungalow Road', distance_km: 0.3 },
        { kind: 'other', name: 'Rajpath Club', distance_km: 0.8 },
      ],
      is_active: true,
      created_at: '2026-09-18T10:00:00Z',
      media: {
        photos: [
          {
            id: 'p1-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 240000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Bright and open living hall with marble flooring and balcony access',
            created_at: '2026-09-18T10:00:00Z',
          },
          {
            id: 'p1-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Modular kitchen with chimney, piped gas line, and quartz countertop',
            created_at: '2026-09-18T10:00:00Z',
          },
          {
            id: 'p1-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Airy master bedroom with wooden wardrobes and ensuite bathroom',
            created_at: '2026-09-18T10:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 98,
      cosine_similarity: 0.98,
      method: 'housing_fit',
      reasons: [
        'Prime Bodakdev location 300m from Judges Bungalow Road.',
        'Split rent matches your target budget perfectly.',
        'Voltas inverter AC installed in all bedrooms.',
      ],
    },
    match_score: 98,
    provider_name: 'Aarav Shah',
  },
  {
    listing: {
      id: 'listing-thaltej-2',
      owner_id: 'provider-devang',
      title: 'Gulmohar Greens Independent Bungalow',
      description: 'Exclusive 4BHK independent bungalow in serene Thaltej. Features a private lawn garden, double car port, rooftop gazebo with terrace, 5kW rooftop solar system, and servant quarter.',
      kind: 'entire_home',
      property_type: '4bhk_plus',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Thaltej',
        pincode: '380059',
      },
      monthly_rent: 58000,
      deposit: 116000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 4,
        },
        notes: 'Torrent Power actual bill offset by 5kW rooftop solar panels.',
      },
      air_conditioning: {
        available: true,
        locations: ['All 4 Bedrooms', 'Ground Floor Living Room'],
        billing_method: 'included_in_electricity',
        notes: 'Daikin 5-star inverter ACs installed throughout the bungalow.',
      },
      available_from: '2026-10-15',
      minimum_stay_months: 11,
      available_spaces: 4,
      furnishing: 'furnished',
      amenities: ['Private Lawn Garden', 'Terrace Gazebo', 'Double Car Port', 'Solar Rooftop', 'Modular Kitchen'],
      nearby_landmarks: [
        { kind: 'public_transport', name: 'Thaltej Metro Station', distance_km: 0.5 },
        { kind: 'workplace', name: 'SG Highway Corporate Road', distance_km: 1.1 },
      ],
      is_active: true,
      created_at: '2026-09-18T10:30:00Z',
      media: {
        photos: [
          {
            id: 'p2-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 260000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Modern bungalow exterior with manicured private front lawn',
            created_at: '2026-09-18T10:30:00Z',
          },
          {
            id: 'p2-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 240000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Spacious ground floor living and dining hall with garden view',
            created_at: '2026-09-18T10:30:00Z',
          },
          {
            id: 'p2-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 230000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'First floor terrace master suite with private sit-out balcony',
            created_at: '2026-09-18T10:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 95,
      cosine_similarity: 0.95,
      method: 'housing_fit',
      reasons: [
        '500m to Thaltej Metro Station for swift commute.',
        'Spacious 4-room bungalow with independent private lawn.',
        'Sperner split: Master Suite ₹18,000 · Garden Room ₹15,000 · Terrace Room ₹13,000 · Guest Room ₹12,000.',
      ],
    },
    match_score: 95,
    provider_name: 'Devang Joshi',
  },
  {
    listing: {
      id: 'listing-navrangpura-3',
      owner_id: 'provider-meera',
      title: 'Stanza Living Elite Co-Living PG',
      description: 'Premium student and young professional PG in prime Navrangpura. Walking distance to CEPT, LD Engineering, and Gujarat University. Includes 3 wholesome pure-veg meals daily, high-speed 300 Mbps Wi-Fi, daily housekeeping, and laundry.',
      kind: 'shared_room',
      property_type: '1rk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Navrangpura',
        pincode: '380009',
      },
      monthly_rent: 13500,
      deposit: 13500,
      electricity: {
        billing_method: 'included_in_rent',
        notes: 'Electricity, high-speed Wi-Fi, and water heating fully included in monthly fee.',
      },
      air_conditioning: {
        available: true,
        locations: ['Private Room'],
        billing_method: 'included_in_rent',
        notes: 'Blue Star split inverter AC included with zero extra electricity bill.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 6,
      available_spaces: 1,
      furnishing: 'furnished',
      amenities: ['3 Daily Veg Meals', 'Daily Housekeeping', '300 Mbps Wi-Fi', 'Biometric Access', 'Laundry Service'],
      nearby_landmarks: [
        { kind: 'university', name: 'CEPT University Campus', distance_km: 0.4 },
        { kind: 'jain_derasar', name: 'Navrangpura Jain Derasar', distance_km: 0.2 },
        { kind: 'university', name: 'Gujarat University', distance_km: 0.6 },
      ],
      is_active: true,
      created_at: '2026-09-18T11:00:00Z',
      media: {
        photos: [
          {
            id: 'p3-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Furnished single occupancy PG room with ergonomic study desk',
            created_at: '2026-09-18T11:00:00Z',
          },
          {
            id: 'p3-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 200000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Community dining hall and evening tea lounge',
            created_at: '2026-09-18T11:00:00Z',
          },
          {
            id: 'p3-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Clean attached bathroom with instant geyser',
            created_at: '2026-09-18T11:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 96,
      cosine_similarity: 0.96,
      method: 'housing_fit',
      reasons: [
        '400m to CEPT University and Navrangpura Jain Derasar.',
        'All utilities, daily cleaning, and pure-veg meals included.',
        'Solo Fair Rent: ₹13,500 all inclusive.',
      ],
    },
    match_score: 96,
    provider_name: 'Meera Patel',
  },
  {
    listing: {
      id: 'listing-satellite-4',
      owner_id: 'provider-rohan',
      title: 'Iscon Platinum Sunlit Flat',
      description: 'Modern 2BHK corner flat near ISKCON temple on Satellite Road. Features bright morning sunlight, piped gas, building swimming pool, and dual Voltas inverter ACs.',
      kind: 'entire_home',
      property_type: '2bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Satellite',
        pincode: '380015',
      },
      monthly_rent: 24000,
      deposit: 48000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 2,
        },
        notes: 'Torrent Power actual bill split 50/50 between two flatmates.',
      },
      air_conditioning: {
        available: true,
        locations: ['Master Bedroom', 'Second Bedroom'],
        billing_method: 'included_in_electricity',
        notes: 'Voltas split inverter ACs in both bedrooms.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 2,
      furnishing: 'semi_furnished',
      amenities: ['Piped Gas', 'Balcony Sit-out', 'Reserved Parking', 'Swimming Pool', 'Gym'],
      nearby_landmarks: [
        { kind: 'temple', name: 'ISKCON Temple', distance_km: 0.5 },
        { kind: 'other', name: 'Shivranjani Crossroads', distance_km: 0.8 },
      ],
      is_active: true,
      created_at: '2026-09-18T12:00:00Z',
      media: {
        photos: [
          {
            id: 'p4-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 240000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Sunlit living room with balcony overlooking Satellite green canopy',
            created_at: '2026-09-18T12:00:00Z',
          },
          {
            id: 'p4-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Modular kitchen with Adani piped gas line and granite breakfast counter',
            created_at: '2026-09-18T12:00:00Z',
          },
          {
            id: 'p4-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Master bedroom with built-in wooden almirah and AC',
            created_at: '2026-09-18T12:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 94,
      cosine_similarity: 0.94,
      method: 'housing_fit',
      reasons: [
        '500m to ISKCON temple and BRTS corridor.',
        'Rent of ₹24,000 fits standard 2-person sharing budget.',
        'Sperner split: Master ₹13,000 · Corner Room ₹11,000.',
      ],
    },
    match_score: 94,
    provider_name: 'Rohan Parekh',
  },
  {
    listing: {
      id: 'listing-sghighway-5',
      owner_id: 'provider-kabir',
      title: 'Zolo Tribe Youth Co-Living Hostel',
      description: 'Vibrant student and tech professional co-living hostel near SG Highway. Offers shared bunk pods, PlayStation gaming lounge, cafeteria with Gujarati/North Indian buffet, and 24/7 power backup.',
      kind: 'shared_room',
      property_type: 'studio',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'SG Highway',
        pincode: '382481',
      },
      monthly_rent: 8500,
      deposit: 8500,
      electricity: {
        billing_method: 'included_in_rent',
        notes: 'All electrical usage, common room AC, and Wi-Fi included in monthly rent.',
      },
      air_conditioning: {
        available: true,
        locations: ['Study Lounge', 'Dorm Pods'],
        billing_method: 'included_in_rent',
        notes: 'Central cooling and split AC during evening study hours.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 3,
      available_spaces: 1,
      furnishing: 'furnished',
      amenities: ['Gaming Zone (PS5)', 'Cafeteria', 'Coworking Lounge', 'Wi-Fi', '24/7 Security Warden'],
      nearby_landmarks: [
        { kind: 'university', name: 'Nirma University', distance_km: 1.5 },
        { kind: 'workplace', name: 'SG Highway IT Corridor', distance_km: 0.8 },
      ],
      is_active: true,
      created_at: '2026-09-18T12:30:00Z',
      media: {
        photos: [
          {
            id: 'p5-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 230000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Vibrant co-living hostel lounge with beanbags and study pods',
            created_at: '2026-09-18T12:30:00Z',
          },
          {
            id: 'p5-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 215000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Clean student bunk room with individual lockable storage and reading lamps',
            created_at: '2026-09-18T12:30:00Z',
          },
          {
            id: 'p5-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 200000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Cafeteria with fresh breakfast buffet setup',
            created_at: '2026-09-18T12:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 92,
      cosine_similarity: 0.92,
      method: 'housing_fit',
      reasons: [
        'Pocket-friendly student rate under ₹10,000/month.',
        'Quick access to SG Highway IT parks and Nirma University.',
        'Solo Fair Rent: ₹8,500 all inclusive.',
      ],
    },
    match_score: 92,
    provider_name: 'Kabir Mehta',
  },
  {
    listing: {
      id: 'listing-vastrapur-6',
      owner_id: 'provider-ananya',
      title: 'Vastrapur Lakeview Residency Flat',
      description: '3BHK lakefront apartment facing the morning sunrise over Vastrapur Lake garden. High-floor corner unit with breezy cross-ventilation, 4 minutes walk to Ahmedabad One Mall and IIM Ahmedabad.',
      kind: 'entire_home',
      property_type: '3bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Vastrapur',
        pincode: '380015',
      },
      monthly_rent: 32000,
      deposit: 64000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 3,
        },
        notes: 'Monthly Torrent Power electricity bill divided equally among 3 occupants.',
      },
      air_conditioning: {
        available: true,
        locations: ['All 3 Bedrooms'],
        billing_method: 'included_in_electricity',
        notes: '1.5-ton split AC installed in each bedroom.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 3,
      furnishing: 'semi_furnished',
      amenities: ['Direct Lake Garden Access', 'Balcony Sit-out', 'High-Speed Elevators', 'Piped Gas', 'Security'],
      nearby_landmarks: [
        { kind: 'park', name: 'Vastrapur Lake Garden', distance_km: 0.1 },
        { kind: 'other', name: 'Ahmedabad One Mall', distance_km: 0.4 },
        { kind: 'university', name: 'IIM Ahmedabad Campus', distance_km: 1.0 },
      ],
      is_active: true,
      created_at: '2026-09-18T13:00:00Z',
      media: {
        photos: [
          {
            id: 'p6-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 245000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Airy balcony facing peaceful morning lake waters',
            created_at: '2026-09-18T13:00:00Z',
          },
          {
            id: 'p6-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 235000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Spacious dining and drawing area with vitrified tiles',
            created_at: '2026-09-18T13:00:00Z',
          },
          {
            id: 'p6-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 215000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Master bedroom with attached bath and corner window',
            created_at: '2026-09-18T13:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 95,
      cosine_similarity: 0.95,
      method: 'housing_fit',
      reasons: [
        '100m to Vastrapur Lake walking track and Amphitheatre.',
        'Sperner split: Lake Master ₹12,500 · South Room ₹10,500 · Quiet Room ₹9,000.',
        'Piped gas and separate AC in all bedrooms.',
      ],
    },
    match_score: 95,
    provider_name: 'Ananya Desai',
  },
  {
    listing: {
      id: 'listing-prahladnagar-7',
      owner_id: 'provider-siddharth',
      title: 'Prarthna Heights Executive Flat',
      description: 'Fully furnished 2BHK flat on Prahlad Nagar Corporate Road. Ideal for corporate professionals. Includes Italian marble flooring, LG smart inverter ACs, water purifier, smart TV, and washing machine.',
      kind: 'entire_home',
      property_type: '2bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Prahlad Nagar',
        pincode: '380015',
      },
      monthly_rent: 28000,
      deposit: 56000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 2,
        },
        notes: 'Torrent Power actual bill split 50/50 each month.',
      },
      air_conditioning: {
        available: true,
        locations: ['Both Bedrooms', 'Drawing Room'],
        billing_method: 'included_in_electricity',
        notes: 'Smart LG inverter ACs in both rooms with low power consumption.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 2,
      furnishing: 'furnished',
      amenities: ['Fully Furnished', 'Italian Marble', 'Smart TV', 'Washing Machine', 'RO Water Purifier'],
      nearby_landmarks: [
        { kind: 'workplace', name: 'Prahlad Nagar Corporate Road', distance_km: 0.3 },
        { kind: 'park', name: 'Prahlad Nagar Garden', distance_km: 0.5 },
      ],
      is_active: true,
      created_at: '2026-09-18T13:30:00Z',
      media: {
        photos: [
          {
            id: 'p7-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 250000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Contemporary executive drawing room with Italian marble floor',
            created_at: '2026-09-18T13:30:00Z',
          },
          {
            id: 'p7-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Modular kitchen fully equipped with RO water and double door fridge',
            created_at: '2026-09-18T13:30:00Z',
          },
          {
            id: 'p7-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'King bed master bedroom with side tables and study desk',
            created_at: '2026-09-18T13:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 93,
      cosine_similarity: 0.93,
      method: 'housing_fit',
      reasons: [
        'Walking distance to Prahlad Nagar corporate hubs.',
        'Fully furnished turnkey setup saves move-in expenses.',
        'Sperner split: Master Suite ₹15,500 · Guest Room ₹12,500.',
      ],
    },
    match_score: 93,
    provider_name: 'Siddharth Dave',
  },
  {
    listing: {
      id: 'listing-sciencecity-8',
      owner_id: 'provider-harshil',
      title: 'Suramya Abode Courtyard Villa / Bungalow',
      description: 'Serene 3BHK independent villa with open central courtyard on Science City Road. Gated township with 24/7 security, lush tree-lined avenues, private front sit-out otla, and solar water heater.',
      kind: 'entire_home',
      property_type: '3bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Science City',
        pincode: '380060',
      },
      monthly_rent: 46000,
      deposit: 92000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 3,
        },
        notes: 'UGVCL submeter actual consumption split 3 ways.',
      },
      air_conditioning: {
        available: true,
        locations: ['All 3 Bedrooms'],
        billing_method: 'included_in_electricity',
        notes: 'Split ACs in all bedrooms with individual remotes.',
      },
      available_from: '2026-10-15',
      minimum_stay_months: 11,
      available_spaces: 3,
      furnishing: 'semi_furnished',
      amenities: ['Private Courtyard', 'Front Sit-out Otla', 'Solar Water Heater', 'Gated Community', 'Car Parking'],
      nearby_landmarks: [
        { kind: 'other', name: 'Science City Ahmedabad', distance_km: 0.7 },
        { kind: 'hospital', name: 'CIMS Multi-speciality Hospital', distance_km: 1.2 },
      ],
      is_active: true,
      created_at: '2026-09-18T14:00:00Z',
      media: {
        photos: [
          {
            id: 'p8-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 250000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Gated courtyard villa with traditional front porch',
            created_at: '2026-09-18T14:00:00Z',
          },
          {
            id: 'p8-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 230000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Open sky central courtyard bringing morning light inside',
            created_at: '2026-09-18T14:00:00Z',
          },
          {
            id: 'p8-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Upper floor bedroom overlooking private garden',
            created_at: '2026-09-18T14:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 91,
      cosine_similarity: 0.91,
      method: 'housing_fit',
      reasons: [
        'Quiet leafy township near Science City.',
        'Sperner split: Courtyard Master ₹17,500 · Terrace Suite ₹15,500 · Garden Bedroom ₹13,000.',
        'Independent bungalow privacy with secure gated community benefits.',
      ],
    },
    match_score: 91,
    provider_name: 'Harshil Vora',
  },
  {
    listing: {
      id: 'listing-ambawadi-9',
      owner_id: 'provider-priya',
      title: 'Oxford Comforts Girls PG',
      description: 'Reputed and safe girls PG in peaceful Ambawadi near Parimal Garden. Homely Gujarati and Jain vegetarian meals included, high security with CCTV and biometric door, laundry and daily room cleaning.',
      kind: 'shared_room',
      property_type: '1rk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Ambawadi',
        pincode: '380006',
      },
      monthly_rent: 11000,
      deposit: 11000,
      electricity: {
        billing_method: 'included_in_rent',
        notes: 'Electricity up to 100 units/room and unlimited Wi-Fi included.',
      },
      air_conditioning: {
        available: true,
        locations: ['All PG Rooms'],
        billing_method: 'included_in_rent',
        notes: 'Split AC provided with individual thermostat controls.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 6,
      available_spaces: 2,
      furnishing: 'furnished',
      amenities: ['Pure Veg Jain Meals', 'Daily Cleaning', 'Biometric Entry', 'CCTV Security', 'Wi-Fi'],
      nearby_landmarks: [
        { kind: 'park', name: 'Parimal Garden', distance_km: 0.4 },
        { kind: 'workplace', name: 'CG Road Commercial Hub', distance_km: 0.9 },
      ],
      is_active: true,
      created_at: '2026-09-18T14:30:00Z',
      media: {
        photos: [
          {
            id: 'p9-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Comfortable twin-sharing furnished room with individual wooden wardrobes',
            created_at: '2026-09-18T14:30:00Z',
          },
          {
            id: 'p9-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 200000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Study corner with book shelves and high speed Wi-Fi connection',
            created_at: '2026-09-18T14:30:00Z',
          },
          {
            id: 'p9-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Clean dining hall where freshly prepared hot meals are served',
            created_at: '2026-09-18T14:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 97,
      cosine_similarity: 0.97,
      method: 'housing_fit',
      reasons: [
        'Strictly verified women-only living space with biometric security.',
        '400m to Parimal Garden morning jogging track.',
        'Sperner split: Private Room ₹11,000 · Shared Bed ₹8,000.',
      ],
    },
    match_score: 97,
    provider_name: 'Priya Trivedi',
  },
  {
    listing: {
      id: 'listing-gandhinagar-10',
      owner_id: 'provider-aditya',
      title: 'The Nest Student Co-Living Hostel',
      description: 'Modern student hostel on PDPU / PDEU Road, Gandhinagar. Designed for university students with college shuttle, breakfast and dinner buffet, high-speed Wi-Fi, and badminton court.',
      kind: 'shared_room',
      property_type: 'studio',
      provider_relationship: 'owner',
      location: {
        city: 'Gandhinagar',
        area: 'PDPU Road',
        pincode: '382007',
      },
      monthly_rent: 9500,
      deposit: 9500,
      electricity: {
        billing_method: 'included_in_rent',
        notes: 'Electricity, air conditioning, and solar water heating included.',
      },
      air_conditioning: {
        available: true,
        locations: ['All Dorm Rooms', 'Study Lounge'],
        billing_method: 'included_in_rent',
        notes: 'Split AC included in monthly package.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 6,
      available_spaces: 2,
      furnishing: 'furnished',
      amenities: ['Buffet Meals', 'College Shuttle', 'Badminton Court', 'Study Lounge', 'High-Speed Wi-Fi'],
      nearby_landmarks: [
        { kind: 'university', name: 'PDEU / PDPU Campus', distance_km: 0.8 },
        { kind: 'workplace', name: 'Infocity Gandhinagar', distance_km: 3.5 },
      ],
      is_active: true,
      created_at: '2026-09-18T15:00:00Z',
      media: {
        photos: [
          {
            id: 'p10-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 240000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Modern student hostel room with individual study desks and storage',
            created_at: '2026-09-18T15:00:00Z',
          },
          {
            id: 'p10-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Quiet 24-hour study library with ergonomic workstations',
            created_at: '2026-09-18T15:00:00Z',
          },
          {
            id: 'p10-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Recreation courtyard and evening outdoor sports area',
            created_at: '2026-09-18T15:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 93,
      cosine_similarity: 0.93,
      method: 'housing_fit',
      reasons: [
        'Direct shuttle connectivity to PDPU and Infocity.',
        'Complete student package including daily meals and Wi-Fi.',
        'Solo Fair Rent: ₹9,500 all inclusive.',
      ],
    },
    match_score: 93,
    provider_name: 'Aditya Solanki',
  },
  {
    listing: {
      id: 'listing-makarba-11',
      owner_id: 'provider-tanvi',
      title: 'Goyal Orchid Whitefield Flat',
      description: 'Peaceful 2BHK flat in Makarba near SG Highway. High-floor apartment with green balcony view, Adani piped gas line, building garden, and reserved covered parking.',
      kind: 'entire_home',
      property_type: '2bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Makarba',
        pincode: '380051',
      },
      monthly_rent: 22000,
      deposit: 44000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 2,
        },
        notes: 'Torrent Power actual bill split 50/50 through UPI.',
      },
      air_conditioning: {
        available: true,
        locations: ['Master Bedroom'],
        billing_method: 'included_in_electricity',
        notes: 'Voltas 1.5-ton split AC in master bedroom.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 2,
      furnishing: 'semi_furnished',
      amenities: ['Society Garden', 'Piped Gas', 'Balcony Sit-out', 'Reserved Parking', '24/7 Security'],
      nearby_landmarks: [
        { kind: 'workplace', name: 'SG Highway Makarba Hub', distance_km: 0.9 },
        { kind: 'public_transport', name: 'Makarba Metro Station', distance_km: 0.6 },
      ],
      is_active: true,
      created_at: '2026-09-18T15:30:00Z',
      media: {
        photos: [
          {
            id: 'p11-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 230000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Clean open drawing room with vitrified tiles and balcony view',
            created_at: '2026-09-18T15:30:00Z',
          },
          {
            id: 'p11-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 215000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Kitchen with stone countertop and utility wash balcony',
            created_at: '2026-09-18T15:30:00Z',
          },
          {
            id: 'p11-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 205000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Master bedroom with built-in cupboards and split AC',
            created_at: '2026-09-18T15:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 89,
      cosine_similarity: 0.89,
      method: 'housing_fit',
      reasons: [
        'Great value rent of ₹11,000 per room average in Makarba.',
        'Quick 600m to Makarba Metro Station.',
        'Sperner split: Master ₹12,000 · Balcony Room ₹10,000.',
      ],
    },
    match_score: 89,
    provider_name: 'Tanvi Bhatt',
  },
  {
    listing: {
      id: 'listing-heritage-12',
      owner_id: 'provider-diya',
      title: 'Heritage Haveli Restoration Flat',
      description: 'Rare restored heritage haveli apartment near Sabarmati Riverfront. High wooden timber ceilings, intricate Gujarati teak wood carvings, private internal courtyard otla, and Daikin AC.',
      kind: 'entire_home',
      property_type: '2bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Riverfront / Pol',
        pincode: '380001',
      },
      monthly_rent: 18000,
      deposit: 36000,
      electricity: {
        billing_method: 'included_in_rent',
        notes: 'Electricity and water included in monthly heritage lease.',
      },
      air_conditioning: {
        available: true,
        locations: ['Both Bedrooms'],
        billing_method: 'included_in_rent',
        notes: 'Daikin inverter split ACs installed.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 2,
      furnishing: 'semi_furnished',
      amenities: ['Teak Wood Carvings', 'Courtyard Otla', 'High Ceilings', 'Riverfront Walk (3 min)'],
      nearby_landmarks: [
        { kind: 'park', name: 'Sabarmati Riverfront Promenade', distance_km: 0.3 },
        { kind: 'other', name: 'Ellis Bridge', distance_km: 0.6 },
      ],
      is_active: true,
      created_at: '2026-09-18T16:00:00Z',
      media: {
        photos: [
          {
            id: 'p12-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 260000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Traditional carved wooden pillars and peaceful interior courtyard',
            created_at: '2026-09-18T16:00:00Z',
          },
          {
            id: 'p12-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 240000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Living salon with high timber ceilings and warm heritage lamps',
            created_at: '2026-09-18T16:00:00Z',
          },
          {
            id: 'p12-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 215000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Cozy bedroom with wooden flooring and private attached bath',
            created_at: '2026-09-18T16:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 90,
      cosine_similarity: 0.9,
      method: 'housing_fit',
      reasons: [
        '300m to Sabarmati Riverfront morning walking track.',
        'Historic architecture with fully modernized AC and plumbing.',
        'Sperner split: Traditional Master ₹10,000 · Otla Room ₹8,000.',
      ],
    },
    match_score: 90,
    provider_name: 'Diya Choksi',
  },
  {
    listing: {
      id: 'listing-sbr-13',
      owner_id: 'provider-neha',
      title: 'Venus Pasadena Luxury Flat',
      description: 'Ultra-luxurious 3BHK high-rise apartment on Sindhu Bhavan Road (SBR). Features false ceiling lighting, modular Italian kitchen, rooftop infinity pool, squash court, and 2 reserved stilt parkings.',
      kind: 'entire_home',
      property_type: '3bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Bodakdev',
        pincode: '380054',
      },
      monthly_rent: 42000,
      deposit: 84000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 3,
        },
        notes: 'Torrent Power actual bill split 3 ways.',
      },
      air_conditioning: {
        available: true,
        locations: ['All 3 Bedrooms', 'Living Room'],
        billing_method: 'included_in_electricity',
        notes: 'Mitsubishi Electric 5-star inverter ACs in all rooms.',
      },
      available_from: '2026-10-15',
      minimum_stay_months: 11,
      available_spaces: 3,
      furnishing: 'semi_furnished',
      amenities: ['Infinity Swimming Pool', 'Squash Court', 'Modular Italian Kitchen', 'Double Stilt Parking', 'Gym'],
      nearby_landmarks: [
        { kind: 'workplace', name: 'Sindhu Bhavan Road (SBR)', distance_km: 0.5 },
        { kind: 'other', name: 'Taj Skyline Ahmedabad', distance_km: 1.0 },
      ],
      is_active: true,
      created_at: '2026-09-18T16:30:00Z',
      media: {
        photos: [
          {
            id: 'p13-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 255000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Luxury drawing room with glass balcony overlooking SBR skyline',
            created_at: '2026-09-18T16:30:00Z',
          },
          {
            id: 'p13-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 235000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Modular Italian kitchen with breakfast island',
            created_at: '2026-09-18T16:30:00Z',
          },
          {
            id: 'p13-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 215000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Master suite with wooden flooring and designer bathroom',
            created_at: '2026-09-18T16:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 96,
      cosine_similarity: 0.96,
      method: 'housing_fit',
      reasons: [
        'Heart of Sindhu Bhavan Road upscale lifestyle hub.',
        'Full building club amenities with infinity pool.',
        'Sperner split: Master Suite ₹16,000 · Club Room ₹13,500 · East Room ₹12,500.',
      ],
    },
    match_score: 96,
    provider_name: 'Neha Panchal',
  },
  {
    listing: {
      id: 'listing-satellite-14',
      owner_id: 'provider-pooja',
      title: 'Royal Heritage Row House / Bungalow',
      description: 'Independent 3BHK duplex row house in Satellite / Jodhpur. Features a private open terrace, front garden otla, dedicated borewell water supply, and piped gas connection.',
      kind: 'entire_home',
      property_type: '3bhk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Satellite',
        pincode: '380015',
      },
      monthly_rent: 38000,
      deposit: 76000,
      electricity: {
        billing_method: 'actual_bill',
        split: {
          method: 'equal',
          split_between: 3,
        },
        notes: 'Torrent Power actual bill split 3 ways.',
      },
      air_conditioning: {
        available: true,
        locations: ['All 3 Bedrooms'],
        billing_method: 'included_in_electricity',
        notes: 'Split AC units in all bedrooms.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 11,
      available_spaces: 3,
      furnishing: 'semi_furnished',
      amenities: ['Private Open Terrace', 'Front Garden Otla', 'Borewell & Corporation Water', 'Piped Gas'],
      nearby_landmarks: [
        { kind: 'other', name: 'Shivranjani Cross Road', distance_km: 0.6 },
        { kind: 'grocery', name: 'Star Bazaar Satellite', distance_km: 1.1 },
      ],
      is_active: true,
      created_at: '2026-09-18T17:00:00Z',
      media: {
        photos: [
          {
            id: 'p14-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 240000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Independent row house facade with private front gate and veranda',
            created_at: '2026-09-18T17:00:00Z',
          },
          {
            id: 'p14-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 230000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Ground floor living room with granite stairs leading to upper floor',
            created_at: '2026-09-18T17:00:00Z',
          },
          {
            id: 'p14-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'First floor bedroom with private terrace access',
            created_at: '2026-09-18T17:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 92,
      cosine_similarity: 0.92,
      method: 'housing_fit',
      reasons: [
        'Central Satellite location with standalone row house privacy.',
        'Private rooftop terrace for evening relaxation.',
        'Sperner split: Master Bedroom ₹14,500 · First Floor Suite ₹13,000 · Ground Room ₹10,500.',
      ],
    },
    match_score: 92,
    provider_name: 'Pooja Modi',
  },
  {
    listing: {
      id: 'listing-ghatlodia-15',
      owner_id: 'provider-chirag',
      title: 'Himalaya Elanza Serviced Studio Flat',
      description: 'Compact self-contained 1BHK / Studio flat in Ghatlodia near Rannapark BRTS. Includes sofa-cum-bed, study table, refrigerator, 1.5-ton split AC, and high-speed Wi-Fi.',
      kind: 'entire_home',
      property_type: 'studio',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Ghatlodia',
        pincode: '380061',
      },
      monthly_rent: 15000,
      deposit: 30000,
      electricity: {
        billing_method: 'fixed_monthly',
        fixed_monthly_amount: 1000,
        notes: 'Flat ₹1,000/month covers electricity and Wi-Fi.',
      },
      air_conditioning: {
        available: true,
        locations: ['Studio Salon'],
        billing_method: 'included_in_rent',
        notes: '1.5-ton inverter AC included in rent.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 6,
      available_spaces: 1,
      furnishing: 'furnished',
      amenities: ['Modular Kitchenette', 'Sofa-cum-Bed', 'Refrigerator', 'Split AC', 'Wi-Fi'],
      nearby_landmarks: [
        { kind: 'public_transport', name: 'Rannapark BRTS Stand', distance_km: 0.2 },
        { kind: 'other', name: 'AEC Crossroads', distance_km: 0.7 },
      ],
      is_active: true,
      created_at: '2026-09-18T17:30:00Z',
      media: {
        photos: [
          {
            id: 'p15-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Cozy private studio apartment with warm lighting and work nook',
            created_at: '2026-09-18T17:30:00Z',
          },
          {
            id: 'p15-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Fitted kitchenette with induction stove and mini-refrigerator',
            created_at: '2026-09-18T17:30:00Z',
          },
          {
            id: 'p15-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 200000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Bright morning daylight from large sliding window',
            created_at: '2026-09-18T17:30:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 88,
      cosine_similarity: 0.88,
      method: 'housing_fit',
      reasons: [
        'Self-contained private studio under ₹15,000 threshold.',
        '200m to Rannapark BRTS for direct bus connectivity.',
        'Solo Fair Rent: ₹15,000 with utilities.',
      ],
    },
    match_score: 88,
    provider_name: 'Chirag Soni',
  },
  {
    listing: {
      id: 'listing-panjrapole-16',
      owner_id: 'provider-rakesh',
      title: 'Shreeji Boys Executive PG',
      description: 'Executive PG for college boys and working professionals near IIM Ahmedabad and Panjrapole. Includes unlimited Wi-Fi, daily housekeeping, North Indian & Gujarati homely meals, and split AC.',
      kind: 'shared_room',
      property_type: '1rk',
      provider_relationship: 'owner',
      location: {
        city: 'Ahmedabad',
        area: 'Panjrapole',
        pincode: '380015',
      },
      monthly_rent: 10500,
      deposit: 10500,
      electricity: {
        billing_method: 'included_in_rent',
        notes: 'Electricity up to 80 units/room included.',
      },
      air_conditioning: {
        available: true,
        locations: ['All PG Rooms'],
        billing_method: 'included_in_rent',
        notes: 'Split AC with remote provided.',
      },
      available_from: '2026-10-01',
      minimum_stay_months: 6,
      available_spaces: 2,
      furnishing: 'furnished',
      amenities: ['Homely Pure Veg Meals', 'Daily Cleaning', 'Fast Wi-Fi', 'Washing Machine', 'Water Cooler'],
      nearby_landmarks: [
        { kind: 'university', name: 'IIM Ahmedabad Old Campus', distance_km: 0.5 },
        { kind: 'other', name: 'Panjrapole Cross Road', distance_km: 0.3 },
      ],
      is_active: true,
      created_at: '2026-09-18T18:00:00Z',
      media: {
        photos: [
          {
            id: 'p16-1',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 210000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 1,
            caption: 'Well-appointed executive PG room with individual study tables and wardrobes',
            created_at: '2026-09-18T18:00:00Z',
          },
          {
            id: 'p16-2',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 200000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 2,
            caption: 'Dining and common lounge with daily newspaper and water cooler',
            created_at: '2026-09-18T18:00:00Z',
          },
          {
            id: 'p16-3',
            kind: 'photo',
            url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&auto=format&fit=crop&q=80',
            thumbnail_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=300&auto=format&fit=crop&q=80',
            content_type: 'image/jpeg',
            byte_size: 220000,
            width: 900,
            height: 600,
            duration_seconds: null,
            position: 3,
            caption: 'Attached bathroom with modern sanitary fittings and geyser',
            created_at: '2026-09-18T18:00:00Z',
          },
        ],
        video: null,
        cover_photo_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&auto=format&fit=crop&q=80',
        photo_count: 3,
        minimum_photos: 3,
        maximum_photos: 6,
        ready: true,
      },
    },
    compatibility: {
      score: 95,
      cosine_similarity: 0.95,
      method: 'housing_fit',
      reasons: [
        '500m walk to IIM Ahmedabad campus.',
        'Daily homemade meals and laundry service included.',
        'Sperner split: Single Occupancy ₹10,500 · Twin Sharing ₹7,000.',
      ],
    },
    match_score: 95,
    provider_name: 'Rakesh Patel',
  },
];
