import type { Questionnaire } from '../types/onboarding';

export const FALLBACK_QUESTIONNAIRE: Questionnaire = {
  version: '1.1',
  introduction:
    'There is no right way to live. Tell us what works for you so we can find compatible homes and people. Optional answers can be skipped; explicit requirements are checked before ranking.',
  sections: [
    {
      id: 'account',
      title: "Let's get to know you",
      questions: [
        {
          field: 'email',
          prompt: 'Which email would you like to sign in with?',
          help_text: 'Private; never shown on discovery cards.',
          input_type: 'email',
          required: true,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: [],
        },
        {
          field: 'password',
          prompt: 'Choose a password',
          help_text: 'Use 10–128 characters.',
          input_type: 'password',
          required: true,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: [],
        },
        {
          field: 'profile.full_name',
          prompt: 'What name would you like people to see?',
          help_text: 'Your display name, up to 100 characters.',
          input_type: 'text',
          required: true,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: [],
        },
        {
          field: 'profile.age',
          prompt: 'How old are you?',
          help_text: 'PropVibe is for adults aged 18 and above.',
          input_type: 'number',
          required: true,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: [],
        },
        {
          field: 'profile.gender',
          prompt: 'How would you like to describe your gender?',
          help_text:
            'You can choose not to share. Specific roommate requirements only match explicitly supplied answers.',
          input_type: 'single_choice',
          required: false,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [
            { value: 'woman', label: 'Woman' },
            { value: 'man', label: 'Man' },
            { value: 'non_binary', label: 'Non binary' },
            { value: 'self_described', label: 'Self described' },
            { value: 'prefer_not_to_say', label: 'Prefer not to say' },
          ],
          used_for: [],
        },
        {
          field: 'profile.occupation',
          prompt: 'What keeps you busy most days?',
          help_text: 'Optional work or study description.',
          input_type: 'text',
          required: false,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: [],
        },
        {
          field: 'profile.bio',
          prompt: 'What would you like a future housemate or provider to know?',
          help_text: 'Optional introduction, up to 1,000 characters.',
          input_type: 'text',
          required: false,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: [],
        },
        {
          field: 'profile.intent',
          prompt: 'What would help you right now?',
          help_text:
            'Choose one primary goal. seek_room joins someone who already has a home; seek_roommate finds someone to search together.',
          input_type: 'single_choice',
          required: true,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [
            { value: 'seek_roommate', label: 'Find a roommate to search together' },
            { value: 'seek_room', label: 'Find an open room in an existing flat' },
            { value: 'seek_entire_home', label: 'Rent an entire home or flat' },
            { value: 'offer_shared_home', label: 'Offer an open room in my flat' },
            { value: 'offer_entire_home', label: 'Offer an entire property' },
          ],
          used_for: ['intent_routing'],
        },
      ],
    },
    {
      id: 'search',
      title: 'Your next home',
      questions: [
        {
          field: 'profile.search.location.city',
          prompt: 'Which city would work for you?',
          help_text: 'One city for this search.',
          input_type: 'text',
          required: true,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter'],
        },
        {
          field: 'profile.search.location.areas',
          prompt: 'Any neighbourhoods you would like to be in?',
          help_text:
            'Optional. Areas and PIN codes are alternative acceptable localities, not a radius lookup.',
          input_type: 'list',
          required: false,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter'],
        },
        {
          field: 'profile.search.location.pincodes',
          prompt: 'Do you have preferred PIN codes?',
          help_text: 'Optional six-digit Indian PIN codes, e.g. 380009.',
          input_type: 'list',
          required: false,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter'],
        },
        {
          field: 'profile.search.budget',
          prompt: 'What monthly rent range feels comfortable?',
          help_text:
            'Supply minimum and maximum INR. Whole-home searches use total tenancy rent; room/roommate searches use your individual share.',
          input_type: 'object',
          required: true,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter', 'rent_affordability'],
        },
        {
          field: 'profile.search.property_types',
          prompt: 'Which home layouts would work?',
          help_text: 'Select at least one. For a room, this is the layout of the entire flat.',
          input_type: 'multi_choice',
          required: true,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [
            { value: 'studio', label: 'Studio' },
            { value: '1rk', label: '1 RK' },
            { value: '1bhk', label: '1 BHK' },
            { value: '2bhk', label: '2 BHK' },
            { value: '3bhk', label: '3 BHK' },
            { value: '4bhk_plus', label: '4 BHK+' },
            { value: 'other', label: 'Other' },
          ],
          used_for: ['hard_filter'],
        },
        {
          field: 'profile.search.move_in_from',
          prompt: "What's your earliest move-in date?",
          help_text: 'YYYY-MM-DD.',
          input_type: 'date',
          required: true,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter'],
        },
        {
          field: 'profile.search.move_in_by',
          prompt: "What's your latest comfortable move-in date?",
          help_text: 'Must be on or after your earliest date.',
          input_type: 'date',
          required: true,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter'],
        },
        {
          field: 'profile.search.stay_months',
          prompt: 'How many months do you expect to stay?',
          help_text: '1–60 months; checked against minimum lease length.',
          input_type: 'number',
          required: true,
          applies_to: ['seek_entire_home', 'seek_room', 'seek_roommate'],
          options: [],
          used_for: ['hard_filter'],
        },
      ],
    },
    {
      id: 'lifestyle',
      title: 'How home feels for you',
      questions: [
        {
          field: 'profile.lifestyle.cleanliness',
          prompt: 'How do you like shared spaces to be kept?',
          help_text: '1: relaxed about clutter; 5: prefer frequent tidying.',
          input_type: 'scale',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.social_energy',
          prompt: 'How much together-time feels good at home?',
          help_text: '1: mostly private time; 5: frequent shared activities.',
          input_type: 'scale',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.guests',
          prompt: 'How often do you tend to host visitors?',
          help_text: '1: rarely; 5: frequently.',
          input_type: 'scale',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.noise_tolerance',
          prompt: 'What sound level feels comfortable at home?',
          help_text: '1: quiet; 5: lively is fine.',
          input_type: 'scale',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.sleep_schedule',
          prompt: 'Which sleep routine is closest to yours?',
          help_text: 'Choose flexible if your routine varies.',
          input_type: 'single_choice',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [
            { value: 'early_bird', label: 'Early bird' },
            { value: 'night_owl', label: 'Night owl' },
            { value: 'flexible', label: 'Flexible' },
          ],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.work_style',
          prompt: 'Where do you usually work or study?',
          help_text: 'This helps people discuss shared space during the day.',
          input_type: 'single_choice',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [
            { value: 'office', label: 'Office' },
            { value: 'hybrid', label: 'Hybrid' },
            { value: 'remote', label: 'Remote' },
            { value: 'varies', label: 'Varies' },
          ],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.diet',
          prompt: 'Which food routine best describes yours?',
          help_text: 'No routine is better than another. You may prefer not to say.',
          input_type: 'single_choice',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [
            { value: 'vegetarian', label: 'Vegetarian' },
            { value: 'vegan', label: 'Vegan' },
            { value: 'jain', label: 'Jain' },
            { value: 'omnivore', label: 'Omnivore' },
            { value: 'other', label: 'Other' },
            { value: 'prefer_not_to_say', label: 'Prefer not to say' },
          ],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.smokes',
          prompt: 'Do you currently smoke?',
          help_text: 'A practical household-fit question, without judgement.',
          input_type: 'boolean',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
        {
          field: 'profile.lifestyle.has_pets',
          prompt: 'Will any pets move in with you?',
          help_text: 'This helps check whether the household can accommodate them.',
          input_type: 'boolean',
          required: true,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['weighted_cosine', 'irving_rankings'],
        },
      ],
    },
    {
      id: 'preferences',
      title: 'What makes sharing comfortable?',
      questions: [
        {
          field: 'profile.roommate_preferences.genders',
          prompt: 'Who would you feel comfortable sharing a home with?',
          help_text: 'Leave empty if open to anyone. Applies only to shared living.',
          input_type: 'multi_choice',
          required: false,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [
            { value: 'woman', label: 'Woman' },
            { value: 'man', label: 'Man' },
            { value: 'non_binary', label: 'Non binary' },
          ],
          used_for: ['mutual_dealbreaker'],
        },
        {
          field: 'profile.roommate_preferences.smoking_ok',
          prompt: 'Would sharing with someone who smokes work for you?',
          help_text: 'No requires a smoke-free household; neutral allows either.',
          input_type: 'boolean',
          required: false,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['mutual_dealbreaker'],
        },
        {
          field: 'profile.roommate_preferences.pets_ok',
          prompt: 'Would living with pets work for you?',
          help_text: 'No excludes households bringing pets; neutral allows either.',
          input_type: 'boolean',
          required: false,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['mutual_dealbreaker'],
        },
        {
          field: 'profile.room_priorities',
          prompt: 'What would you value most in your own room?',
          help_text:
            'Optional 0–5 priorities: size, private_bathroom, balcony, natural_light, quiet. Used to seed Rent Harmony valuations.',
          input_type: 'object',
          required: false,
          applies_to: ['seek_room', 'seek_roommate', 'offer_shared_home'],
          options: [],
          used_for: ['rent_valuation_onboarding'],
        },
      ],
    },
    {
      id: 'offering',
      title: "The home or space you're offering",
      questions: [
        {
          field: 'offering.title',
          prompt: 'How would you describe the space in one line?',
          help_text: '3–160 characters.',
          input_type: 'text',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.description',
          prompt: 'What else should someone know about the home?',
          help_text: 'Optional details, up to 3,000 characters.',
          input_type: 'text',
          required: false,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.kind',
          prompt: 'Are you offering the whole home or space within it?',
          help_text:
            'Whole-home intent requires entire_home; shared-home intent requires private_room or shared_room.',
          input_type: 'single_choice',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [
            { value: 'entire_home', label: 'Entire home' },
            { value: 'private_room', label: 'Private room' },
            { value: 'shared_room', label: 'Shared room' },
          ],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.property_type',
          prompt: "What's the layout of the whole home?",
          help_text: 'Choose the flat layout even if offering just one room.',
          input_type: 'single_choice',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [
            { value: 'studio', label: 'Studio' },
            { value: '1rk', label: '1 RK' },
            { value: '1bhk', label: '1 BHK' },
            { value: '2bhk', label: '2 BHK' },
            { value: '3bhk', label: '3 BHK' },
            { value: '4bhk_plus', label: '4 BHK+' },
          ],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.provider_relationship',
          prompt: 'Do you own this home or currently rent it?',
          help_text: 'This is self-reported; it is not an ownership verification badge.',
          input_type: 'single_choice',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [
            { value: 'owner', label: 'Owner' },
            { value: 'tenant', label: 'Tenant' },
          ],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.location',
          prompt: 'Where is the home located?',
          help_text: 'City, area, and six-digit PIN code.',
          input_type: 'object',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.monthly_rent',
          prompt: 'What monthly rent are you asking?',
          help_text: 'INR for whole tenancy, or per incoming person for shared homes.',
          input_type: 'number',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.deposit',
          prompt: 'Is a refundable deposit requested?',
          help_text: 'INR; defaults to zero.',
          input_type: 'number',
          required: false,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [],
          used_for: ['listing_discovery'],
        },
        {
          field: 'offering.available_from',
          prompt: 'When can someone move in?',
          help_text: 'YYYY-MM-DD.',
          input_type: 'date',
          required: true,
          applies_to: ['offer_entire_home', 'offer_shared_home'],
          options: [],
          used_for: ['listing_discovery'],
        },
      ],
    },
    {
      id: 'media',
      title: 'Bring your profile and home to life',
      questions: [
        {
          field: 'media.profile.photos',
          prompt: 'Add 3–6 photos that help people get to know you.',
          help_text:
            'Choose clear, distinct photos. The first is your cover and the rest form your swipe-card carousel.',
          input_type: 'photos',
          required: true,
          applies_to: [
            'seek_entire_home',
            'seek_room',
            'seek_roommate',
            'offer_entire_home',
            'offer_shared_home',
          ],
          options: [],
          used_for: ['profile_carousel', 'discovery_readiness'],
          upload_endpoint: '/api/media/profile/photos',
          minimum_files: 3,
          maximum_files: 6,
          accepted_types: ['image/jpeg', 'image/png', 'image/webp'],
        },
      ],
    },
  ],
};
